### ISSUE TITLE
Support several PgContext in indexMaintenance.get* methods

### ISSUE THREAD

**Issue by SButterfly** [mfvanek/pg-index-health#80]
It is needed, when you want to run checks on several schemas in cluster.
Or in all schemas

**Comment by kondratyev-nv** [comment]
@SButterfly Thank you for the issue! I think it would complicate things a lot. It will either require rewriting SQL queries to support multiple schemas or executing each query for each schema. In the second case, I don't see why it would be any better than creating a loop over multiple PgContexts in client code.

@mfvanek What do you think?

**Comment by SButterfly** [comment]
> In the second case, I don't see why it would be any better than creating a loop over multiple PgContexts in client code.

It would be better,  because clients will write less code. that's all :)

**Comment by mfvanek** [comment]
> @SButterfly Thank you for the issue! I think it would complicate things a lot. It will either require rewriting SQL queries to support multiple schemas or executing each query for each schema. In the second case, I don't see why it would be any better than creating a loop over multiple PgContexts in client code.
> 
> @mfvanek What do you think?

I agree with Nikolay. You can iterate over multiple schemas in client code. There are tons of examples in unit tests how to do this using JUnit 5.
This issue might make sense when we consider the multitenancy architecture.
If we have several schemas with the same structure for different clients, we need to collect and aggregate health data from all schemas in order to figure out which indexes are unused and may be safely deleted.
But right now I don't have plans to support multitenancy.

**Comment by mfvanek** [comment]
@SButterfly 
Could you please provide a code snippet which might be improved with new library methods?

**Comment by SButterfly** [comment]
```java
    protected List<IndexWithNulls> getIndexesWithNullValues() {
        return schemas.stream()
            .flatMap(schema -> indexMaintenance.getIndexesWithNullValues(schema).stream())
            .collect(Collectors.toList());
    }
```
